version: "3"
services:
  mongo_foody:
    container_name: mongo_foodies
    image: mongo
    network_mode: "host"
    volumes:
      - ./db:/data/db
  foody:
    container_name: foody
    environment:
      - TZ=Asia/Bangkok
    network_mode: "host"
    build: .
